name: NetBattleRoyal
version: $version
author: anblusis
main: io.github.anblusis.netBattleRoyal.main.NetBattleRoyal
api-version: '1.21'
libraries:
  - io.github.anblusis:tap-core:1.0.3
  - xyz.icetang.lib:invfx-core:3.3.3
  - io.github.anblusis:kommand-core:1.0.1

